name: CI

on:
  pull_request:
  push:
    # Filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - beta
      - 'v*'
      - /^greenkeeper.*$/

    # Always run CI for tags
    tags:
      - '*'

  # Early issue detection: run CI weekly on Sundays
  schedule:
  - cron:  '0 6 * * 0'

jobs:
  test-mocha:
    name: Mocha Tests - ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      matrix:
        node-version: ['10', '12']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
          npm-version: 4
          yarn-version: 1.22

      - name: Remove test-packages
        run: |
          rm -rf test-packages
      - name: Yarn Install
        working-directory: ./packages/ember-cli-fastboot
        run: |
          yarn install --ignore-engines --frozen-lockfile
      - name: Run Mocha Tests
        working-directory: ./packages/ember-cli-fastboot
        run: |
          npm --version
          yarn test:mocha
